---
title: "Quality Control Tests"

bibliography: references/cmp_threshold_references.bib
---

**DRAFT April 14, 2023**

**Although it is beyond the OOI scope to produce their own analysis-ready data products for the BGC sensors, OOI does undertake initial data processing as well as some basic QA/QC.**

To ensure high-quality data products, the Centre for Marine Applied Research applies automated and "human in the loop" quality control (QC) processes to the Coastal Monitoring Program data.

An automated QC test is an algorithm that evaluates each data record and assigns a flag to the record indicating the test results. These flags are typically reviewed by human experts, which is referred to as "human in the loop" QC. End users can then filter the data set for records that meet their quality criteria [@RN26831].

Numerous QC tests and flagging schemes exist and have been applied to oceanographic data sets [e.g., Appendix A in @RN26831; OOI ref as example of different tests]. CMAR has adopted the well-known QARTOD tests and flagging scheme, which is applied by the U.S. Integrated Ocean Observing System (IOOS) and other ocean observing entities [see Table 1 of @RN25921].

QARTOD stands for the "Quality Assurance / Quality Control of Real-Time Oceanographic Data". It is a project that grew from a 2003 grassroots effort to develop guidelines for high-quality oceanographic data. From 2012 to 2019, QARTOD developed 13 Quality Control manuals covering 14 ocean variables, plus additional supporting materials [@RN25921]. Each QC manual is subjected to three iterations of formal review by subject-matter experts, with the final round soliciting international reviews. Published manuals are updated as needed to reflect new technology, additional knowledge, or growth of the Project [@RN25921].

The QARTOD flag scheme has 5 levels, as described in @tbl-qartod-flags. 

| **Flag**                       | **Description**                                                                                                                                                                      |
|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Pass - 1]{style="color: #009200;"}                       | [Data have passed critical real-time quality control tests and are deemed adequate for use as preliminary data.]{style="color: #009200;"}                                                                       |
| [Not evaluated - 2]{style="color: #c4c1a5;"}              | [Data have not been QC-tested, or the information on quality is not available.]{style="color: #c4c1a5;"}                                                                                                        |
| [Suspect or Of High Interest- 3]{style="color: #EDA247;"} | [Data are considered to be either suspect or of high interest to data providers and users. They are flagged suspect to draw further attention to them by operators.]{style="color: #EDA247;"}                   |
| [Fail - 4]{style="color: #DB4325;"}                       | [Data are considered to have failed one or more critical real-time QC checks. If they are disseminated at all, it should be readily apparent that they are not of acceptable quality.]{style="color: #DB4325;"} |
| [Missing data - 9]{style="color: #5A5A5A;"}               | [Data are missing; used as a placeholder.]{style="color: #5A5A5A;"}                                                     |

: QARTOD flag scheme [@RN25922]. {#tbl-qartod-flags}

QARTOD manuals define QC tests for the 14 variables. For each variable, the tests are grouped into three categories: Required, Strongly Recommended, and Suggested. The Required tests provide the minimum level of QC, and should be easy to implement. However, it is recognized that there are circumstances where these tests are not applicable [@RN25922]. Codable instructions are included with the description of each test to facilitate implementation of automated data checking [@RN25921].

QARTOD manuals focus on QC of real-time data (e.g., minimal delay from when data are recorded to when they are ready for use; however, it is acknowledged that other data may  benefit from QARTOD QC [@RN25922]. The CMAR Coastal Monitoring Program Water Quality Data is not processed in real-time. Instead, data is logged by individual sensors, and typically offloaded for processing every 6 - 12 months. Some QARTOD tests were therefore not applicable to this data, and it was necessary and / or advantageous to modify some of the tests to reflect the nature of the data processing. More detail on these changes is provided in the appropriate sections below.

QC tests require thresholds that determine the results of the test. For example, records greater than the maximum value that can be recorded by a sensor should fail a simple maximum value test. Choosing appropriate thresholds for each test and variable is a key part of the QC effort. The operator (data provider) is responsible for selecting thresholds for QARTOD tests, and thresholds should be based on historical data when possible [@RN25922; @RN15382; add ooi].  

This document describes the tests applied for each variable, and the methods for selecting the most appropriate thresholds. Where possible, these thresholds were determined from historical data, which provide a baseline of "normal" and "outlying" conditions. The historical data used here was the Coastal Monitoring Program Water Quality data sets submitted to the [Nova Scotia Open Data Portal](https://data.novascotia.ca/browse?q=coastal%20monitoring&sortBy=relevance) in December 2022. Preliminary quality control measures (e.g., obvious outliers and suspected biofouling removed) were applied to these datasets before submission. Additionally, freshwater and other outlier stations were excluded from the threshold analysis to provide a better representation of "normal" conditions.

These thresholds should be re-evaluated and re-calculated if necessary in several years, when more data is available.


**add test table here**