---
title: "Temperature"
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 600, fig.width = 8)

library(dplyr)
library(DT)
library(here)
library(ggplot2)
library(leaflet)
library(lubridate)
library(plotly)
library(quarto)
library(RColorBrewer)
library(readr)
library(tidyr)

theme_set(theme_light())

dt_options <- list(
      dom = 'ft',
      paging = FALSE,
      searching = TRUE,
      scrollY = "550px",
      pageLength = 500,
      columnDefs = list(list(className = 'dt-center', targets = "_all"))
)

# summarized data 
dat_summary <- read_csv(
  here("data/summary_filtered_data.csv"), show_col_types = FALSE
) %>% 
  filter(variable == "Temperature")

```


## General Overview

## CMAR Measurements


### Figure 2
```{r}
#| label: fig-temp-n-obs
#| fig-height: 8
#| fig-cap: The number of temperatures observations in each county. 
county <- dat_summary %>% 
  filter(group == "county") %>% 
  select(-c(variable, units, year, depth, month, station))

p  <- ggplot(county, aes(n, county)) +
  geom_col(
    position = position_dodge2(preserve = "single", reverse = TRUE, padding = 0)
  ) +
  scale_y_discrete(name = "", limits = rev) +
  scale_x_continuous("Number of Temperature Records")

ggplotly(p)
```
