---
title: "Overview"
---

# Quality Control

CMAR applies automated and "human in the loop" quality control (QC) processes to the Coastal Monitoring Program Water Quality data. 

Note that it is beyond the scope of the Program to produce analysis-ready data products for all potential users, and some users may wish to apply additional QC.


## Quality Control Tests

An automated QC test is an algorithm that evaluates each data record and assigns a flag to the record indicating the test results. These flags are typically reviewed by human experts, which is referred to as "human in the loop" QC. End users can then filter the data set for records that meet their quality criteria [@RN26831].

Numerous QC flagging schemes and tests exist and have been applied to oceanographic data sets [e.g., Appendix A in @RN26831]. CMAR has adopted the well-known QARTOD flag scheme and several QARTOD tests, which are applied by the U.S. Integrated Ocean Observing System (IOOS) and other ocean observing entities [see Table 1 of @RN25921].

## QARTOD Guidance

*shorten this para?*

QARTOD stands for the ["Quality Assurance / Quality Control of Real-Time Oceanographic Data"](https://ioos.noaa.gov/project/qartod/). It is a project that grew from a 2003 grassroots effort to develop guidelines for high-quality oceanographic data. From 2012 to 2019, QARTOD developed 13 Quality Control manuals covering 14 ocean variables, plus additional supporting materials [@RN25921]. Each QC manual is subjected to three iterations of formal review by subject-matter experts, with the final round soliciting international reviews. Published manuals are updated as needed to reflect new technology, additional knowledge, or growth of the Project [@RN25921].

QARTOD manuals focus on QC of real-time data[^1], but acknowledge that other data types may also benefit from these flags and tests [@RN25922]. The CMAR Coastal Monitoring Program data is not processed in real-time[^2]. Instead, data is logged and offloaded from the sensors for processing every 6 - 12 months. Some QARTOD guidance was therefore not applicable to this data, and procedures were adapted to reflect the nature of CMAR data and processing.

[^1]: e.g., minimal delay from when data are recorded to when they are ready for use

[^2]: due to technical, logistical, and budget constraints

## Flag Scheme

CMAR has adopted the QARTOD flag scheme (@tbl-qartod-flags) with minor adaptations. Details on how the QARTOD flag scheme was developed is provided in @RN26831. 

| **Flag**                       | **Description**                                                                                                                                                                      |
|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Pass - 1]{style="color: #009200;"}                       | [Data have passed critical real-time quality control tests and are deemed adequate for use as preliminary data.]{style="color: #009200;"}                                                                       |
| [Not evaluated - 2]{style="color: #c4c1a5;"}              | [Data have not been QC-tested, or the information on quality is not available.]{style="color: #c4c1a5;"}                                                                                                        |
| [Suspect or Of High Interest- 3]{style="color: #EDA247;"} | [Data are considered to be either suspect or of high interest to data providers and users. They are flagged suspect to draw further attention to them by operators.]{style="color: #EDA247;"}                   |
| [Fail - 4]{style="color: #DB4325;"}                       | [Data are considered to have failed one or more critical real-time QC checks. If they are disseminated at all, it should be readily apparent that they are not of acceptable quality.]{style="color: #DB4325;"} |
| [Missing data - 9]{style="color: #5A5A5A;"}               | [Data are missing; used as a placeholder.]{style="color: #5A5A5A;"}                                                     |

: QARTOD flag scheme [@RN25922]. {#tbl-qartod-flags}

The main CMAR adaptation to this flag scheme is that the [Missing data]{style="color: #5A5A5A;"} flag is not used. This flag is meant to alert real-time operators that an expected observation was not received, and may trigger efforts to fix recording and transmission issues. Since CMAR does not receive real-time data, this placeholder flag was deemed unnecessary. Note that data gaps may still occur due to sensor failure (e.g., battery failure), delays between retrieval and re-deployment, and vandalism. It is the responsibility of the data users to identify and address these data gaps if required.

Note that QARTOD uses a flag of [3]{style="color: #EDA247;"} to denote observations that are [Suspect]{style="color: #EDA247;"} (e.g., of dubious quality) **or** [Of High Interest]{style="color: #EDA247;"} (e.g., an unusual event). This is meant to encourage human in the loop decisions making [@RN25922]. Where possible, CMAR has defined when these test results are likely [Suspect]{style="color: #EDA247;"} vs. [Of High Interest]{style="color: #EDA247;"}, although data users should inspect these records carefully before deciding how to use (or discard) them.

## Tests

As of February 2024, CMAR applies 5 QC tests to the Coastal Monitoring Program Water Quality data (@tbl-cmar_tests). Click [here](../pages/qc_tests.qmd) for more detail on each test,

*order of tests??*


| Test | Description | Reference |
|---|-----|---|
| Climatology  | Flags observations that are statistical outliers for a given month. | @RN26562, @RN24432, @RN26877 |
| Depth Crosscheck[^3] | Flags deployments where the sensor depth at low tide is different from the measured depth at low tide. | CMAR |
| Gross Range | Flags observations that fall outside of the sensor measurement range and observations that are statistical outliers. | @RN26562, @RN24432 |
| Rolling Standard Deviation | Flags observations with statistically high rolling standard deviation (e.g., multiple-value spikes). | CMAR |
| Spike | Flags single-value spikes. | @RN26562, @RN24432 |


: Automated Quality Control tests applied to Water Quality Data. {#tbl-cmar_tests}

[^3]: note that this is a deployment-level test. See xx for more information.


### Thresholds

Each QC test requires threshold(s) that determine the results of the test. Choosing appropriate thresholds for each test and variable is a key part of the QC effort. The operator (data provider) is responsible for selecting thresholds for QARTOD tests, and thresholds should be based on historical data when possible [@RN25922; @RN15382; @RN26877]. 

*Make this more about CMAR?*

The `Thresholds` link under each variable dropdown menu details how the threshold(s) for each test were selected.



# Delete

QARTOD manuals define real-time QC tests for 14 variables. For each variable, the tests are grouped into three categories: Required, Strongly Recommended, and Suggested. Tests increase in complexity and typically decrease in utility [@RN26562]. Not all tests can be implemented in all situations [@RN26562].

|                      |         |                        |
|----------------------|---------|------------------------|
| Required             | Test 1  | Gap Test               |
| Required             | Test 2  | Syntax Test            |
| Required             | Test 3  | Location Test          |
| Required             | Test 4  | Gross Range Test       |
| Required             | Test 5  | Climatological Test    |
| Strongly Recommended | Test 6  | Spike Test             |
| Strongly Recommended | Test 7  | Rate of Change Test    |
| Strongly Recommended | Test 8  | Flat Line Test         |
| Suggested            | Test 9  | Multi-Variate Test     |
| Suggested            | Test 10 | Attenuated Signal Test |
| Suggested            | Test 11 | Neighbor Test          |
| Suggested[^3]        | Test 12 | TS Curve/Space Test    |
| Suggested[^3]        | Test 13 | Density Inversion Test |

: QARTOD tests for temperature, salinity, and dissolved oxygen [@RN24432; @RN26562]. {#tbl-tests}

[^3]: for temperature and salinity only; not Suggested for dissolved oxygen

These tests were evaluated to determine their suitability and value for the Coastal Monitoring Program data. The key tests selected were the Gross Range Test and the Climatological test. The Rate of Change Test was modified and re-named the "Rolling Standard Deviation Test". A version of the Location Test is applied early in the data processing pipeline. Incorrect coordinates are highlighted and fixed before data processing continues, so no flag is applied. Additional details on these tests is found [here](../pages/qc_tests.qmd).

The remaining tests were not applied because they were designed for real-time data or added little value for the additional complexity.

Test 1 and Test 2 are meant to identify gaps and syntax errors in real time so that the errors can be fixed and the record resume. They are not applicable to this data and were not implemented. Similarly, the Flat Line test is meant to identify and address sensor failure. Another reason this Test was not applied is that some sensors used for the Program have limited sensitivity[^4], so multiple consecutive records with the same value are expected.

[^4]: 1 decimal place

The Suggested tests were considered too complicated for little additional value for this first round of automated QC, although they may be implemented in the future. In particular, the "Multi-Variate Test" may be useful for data from sensors that record multiple variables.



