---
title: "Quality Control"
---

It is beyond the scope of the Coastal Monitoring Program to produce analysis-ready data products for all potential users. However, CMAR does apply some automated and "human in the loop" quality control (QC) processes to the data. Some users may wish to apply additional QC.

## Quality Control Tests

An automated QC test is an algorithm that evaluates each data record and assigns a flag to the record indicating the test results. These flags are typically reviewed by human experts, which is referred to as "human in the loop" QC. End users can then filter the data set for records that meet their quality criteria [@RN26831].

Numerous QC flagging schemes and tests exist and have been applied to oceanographic data sets [e.g., Appendix A in @RN26831]. CMAR has adopted the well-known QARTOD flags and tests, which are applied by the U.S. Integrated Ocean Observing System (IOOS) and other ocean observing entities [see Table 1 of @RN25921].

## QARTOD

QARTOD stands for the "Quality Assurance / Quality Control of Real-Time Oceanographic Data". It is a project that grew from a 2003 grassroots effort to develop guidelines for high-quality oceanographic data. From 2012 to 2019, QARTOD developed 13 Quality Control manuals covering 14 ocean variables, plus additional supporting materials [@RN25921]. Each QC manual is subjected to three iterations of formal review by subject-matter experts, with the final round soliciting international reviews. Published manuals are updated as needed to reflect new technology, additional knowledge, or growth of the Project [@RN25921].

### Flag Scheme

The QARTOD flag scheme has 5 levels, as described in @tbl-qartod-flags. More detail on how this flag scheme was developed is provided in @RN26831.

| **Flag**                       | **Description**                                                                                                                                                                      |
|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Pass - 1]{style="color: #009200;"}                       | [Data have passed critical real-time quality control tests and are deemed adequate for use as preliminary data.]{style="color: #009200;"}                                                                       |
| [Not evaluated - 2]{style="color: #c4c1a5;"}              | [Data have not been QC-tested, or the information on quality is not available.]{style="color: #c4c1a5;"}                                                                                                        |
| [Suspect or Of High Interest- 3]{style="color: #EDA247;"} | [Data are considered to be either suspect or of high interest to data providers and users. They are flagged suspect to draw further attention to them by operators.]{style="color: #EDA247;"}                   |
| [Fail - 4]{style="color: #DB4325;"}                       | [Data are considered to have failed one or more critical real-time QC checks. If they are disseminated at all, it should be readily apparent that they are not of acceptable quality.]{style="color: #DB4325;"} |
| [Missing data - 9]{style="color: #5A5A5A;"}               | [Data are missing; used as a placeholder.]{style="color: #5A5A5A;"}                                                     |

: QARTOD flag scheme [@RN25922]. {#tbl-qartod-flags}

### Tests

QARTOD manuals define QC tests for the 14 variables. For each variable, the tests are grouped into three categories: Required, Strongly Recommended, and Suggested. The Required tests provide the minimum level of QC, and should be easy to implement. However, it is recognized that there are circumstances where these tests are not applicable [@RN25922]. Codable instructions are included with the description of each test to facilitate implementation of automated data checking [@RN25921].


|                      |         |                        |
|----------------------|---------|------------------------|
| Required             | Test 1  | Gap Test               |
| Required             | Test 2  | Syntax Test            |
| Required             | Test 3  | Location Test          |
| Required             | Test 4  | Gross Range Test       |
| Required             | Test 5  | Climatological Test    |
| Strongly Recommended | Test 6  | Spike Test             |
| Strongly Recommended | Test 7  | Rate of Change Test    |
| Strongly Recommended | Test 8  | Flat Line Test         |
| Suggested            | Test 9  | Multi-Variate Test     |
| Suggested            | Test 10 | Attenuated Signal Test |
| Suggested            | Test 11 | Neighbor Test          |
| Suggested[^1]        | Test 12 | TS Curve/Space Test    |
| Suggested[^1]        | Test 13 | Density Inversion Test |

: QARTOD tests for temperature, salinity, and dissolved oxygen [@RN24432; @RN26562]. {#tbl-tests}

[^1]: For temperature and salinity only; not Suggested for dissolved oxygen

QARTOD manuals focus on QC of real-time data[^3], although the manuals acknowledge that other data types may also benefit from these flags and tests [@RN25922]. The CMAR Coastal Monitoring Program data is not processed in real-time. Instead, data is logged and offloaded for processing every 6 - 12 months. Some QARTOD tests were therefore not applicable to this data, and it was necessary and / or advantageous to modify some tests to reflect the nature of the data and processing. 

For example, Test 1 and Test 2 are meant to identify gaps and syntax errors in real time so that the errors can be fixed and the record resume. They are therefore not applicable to the Coastal Monitoring Program data sets and were not implemented. Most of the remaining Required and Implemented tests were applied, but the Suggested tests are beyond the capacity of the current Data Governance team. These additional tests could be implemented in the future.

[^3]: e.g., minimal delay from when data are recorded to when they are ready for use

### Thresholds

QC tests require thresholds that determine the results of the test. Choosing appropriate thresholds for each test and variable is a key part of the QC effort. The operator (data provider) is responsible for selecting thresholds for QARTOD tests, and thresholds should be based on historical data when possible [@RN25922; @RN15382; @RN26877].  

